name: C Unit Testing Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y gcc make libcunit-dev

      - name: Compile the code
        run: gcc -o test_queue queue.c test_queue.c -lcunit

      - name: Run tests
        run: ./test_queue
